### ISSUE TITLE
How to use the streaming API?

### ISSUE THREAD

**Issue by Alan-FGR** [MichaelYusko/GitterPy#39]
Hello there.

I'm trying to use the streaming API, but I couldn't figure out how exactly. `gitter.stream.chat_messages('gitterHQ/sandbox')` never returns and doesn't provide a callback or something I could use to iterate. I've checked the tests but there's no code for streaming there too. How can I for example print the messages are they're streamed?

Thanks in advance.

**Comment by MichaelYusko** [comment]
@Alan-FGR I found an little bug, I'll fix it in 3-4 days, also update the README file, with examples, how to use streams, happy coding!

**Comment by MichaelYusko** [comment]
@Alan-FGR Fixed, also update examples, in README file.

Try this one.
```
response = gitter.stream.chat_messages('gitterHQ/sandbox')

for stream_messages in response.iter_lines():
    if stream_messages:
        print(stream_messages)
```


One moment, for now data will be return in `bytes` format, in one or two week, I'll add some helpers for this case. And with `stream` objects, would be work comfortable.

**Comment by Alan-FGR** [comment]
@MichaelYusko thank you for the update! However, for some reason it still doesn't work here, that same line (`gitter.stream.chat_messages('gitterHQ/sandbox')`) still never returns. I can send messages to the room so I believe it's not a permission problem.

**Comment by MichaelYusko** [comment]
@Alan-FGR You are welcome, and thanks for the report.

Happy coding:)
